// AudioNavigator configuration, DOM references, state, and i18n.
const fileInput = document.querySelector("#fileInput");
const APP_VERSION = "1.1.0";
const APP_VERSION_CHANNEL = "";
const APP_VERSION_LABEL = APP_VERSION_CHANNEL ? `${APP_VERSION}-${APP_VERSION_CHANNEL}` : APP_VERSION;
window.AudioNavigator = window.AudioNavigator || {};
window.APP_VERSION = APP_VERSION;
window.APP_VERSION_CHANNEL = APP_VERSION_CHANNEL;
window.APP_VERSION_LABEL = APP_VERSION_LABEL;
const appShell = document.querySelector(".app-shell");
const installButton = document.querySelector("#installButton");
const settingsButton = document.querySelector("#settingsButton");
const settingsBackdrop = document.querySelector("#settingsBackdrop");
const settingsModal = document.querySelector("#settingsModal");
const settingsClose = document.querySelector("#settingsClose");
const viewportWarning = document.querySelector("#viewportWarning");
const globalDropOverlay = document.querySelector("#globalDropOverlay");
const pwaUpdateNotice = document.querySelector("#pwaUpdateNotice");
const pwaUpdateRestart = document.querySelector("#pwaUpdateRestart");
const licenseButton = document.querySelector("#licenseButton");
const licenseBackdrop = document.querySelector("#licenseBackdrop");
const licenseClose = document.querySelector("#licenseClose");
const resetSettings = document.querySelector("#resetSettings");
const languageControl = document.querySelector(".language-control");
const languageSelect = document.querySelector("#languageSelect");
const dropOpenButton = document.querySelector("#dropOpenButton");
const dropZone = document.querySelector("#dropZone");
const dropError = document.querySelector("#dropError");
const playerPanel = document.querySelector("#playerPanel");
const waveformWrap = document.querySelector(".waveform-wrap");
const canvas = document.querySelector("#waveformCanvas");
const waveformSeekHint = document.querySelector("#waveformSeekHint");
const ctx = canvas.getContext("2d");
const fileName = document.querySelector("#fileName");
const fileDetails = document.querySelector("#fileDetails");
const statusText = document.querySelector("#statusText");
const playButton = document.querySelector("#playButton");
const jumpBack = document.querySelector("#jumpBack");
const jumpForward = document.querySelector("#jumpForward");
const jumpAmount = document.querySelector("#jumpAmount");
const jumpAmountValue = document.querySelector(".jump-amount-value");
const jumpAmountMenu = document.querySelector("#jumpAmountMenu");
const jumpAmountOptions = [...document.querySelectorAll("#jumpAmountMenu [role='option']")];
const languageValue = document.querySelector(".language-value");
const languageMenu = document.querySelector("#languageMenu");
const languageOptions = [...document.querySelectorAll("#languageMenu [role='option']")];
const timeline = document.querySelector("#timeline");
const currentTime = document.querySelector("#currentTime");
const durationText = document.querySelector("#duration");
const speedSlider = document.querySelector("#speedSlider");
const speedValue = document.querySelector("#speedValue");
const volumeSlider = document.querySelector("#volumeSlider");
const volumeValue = document.querySelector("#volumeValue");
const volumeIcon = document.querySelector(".volume-control .ui-icon");
const nextAudio = document.querySelector("#nextAudio");
const loadingOverlay = document.querySelector("#loadingOverlay");
const loadingTitle = document.querySelector("#loadingTitle");
const loadingDetail = document.querySelector("#loadingDetail");
const loadingProgressBar = document.querySelector("#loadingProgressBar");
const loadingProgressTrack = document.querySelector(".progress-track");
const themeColorMeta = document.querySelector("meta[name='theme-color']");
const colorSchemeQuery = window.matchMedia?.("(prefers-color-scheme: dark)");
const themeOptions = [...document.querySelectorAll("input[name='themeMode']")];
const silenceThresholdInput = document.querySelector("#silenceThresholdInput");
const silenceThresholdValue = document.querySelector("#silenceThresholdValue");
const minSilenceInput = document.querySelector("#minSilenceInput");
const minSilenceValue = document.querySelector("#minSilenceValue");
const minAudibleInput = document.querySelector("#minAudibleInput");
const minAudibleValue = document.querySelector("#minAudibleValue");

const translations = {
  en: {
    language: "Language",
    settings: "Settings",
    closeSettings: "Close settings",
    closeLicenses: "Close licenses",
    displaySettings: "Display",
    theme: "Theme",
    themeAuto: "Auto",
    themeDark: "Dark",
    themeLight: "Light",
    detectionSettings: "Silence detection",
    silenceThreshold: "Silence threshold",
    minSilenceLength: "Minimum silence length",
    minAudibleLength: "Minimum audible length",
    keyboardShortcuts: "Keyboard shortcuts",
    keySpace: "Space",
    keyEscape: "Esc",
    shortcutPlayPause: "Play or pause",
    shortcutJumpBack: "Jump back",
    shortcutJumpForward: "Jump forward",
    shortcutNextSection: "Next section",
    shortcutCloseSettings: "Close settings",
    resetDefaults: "Reset defaults",
    licenses: "Licenses",
    openSourceLicenses: "Open source licenses",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Material Symbols fonts are provided by Google and licensed under the Apache License, Version 2.0.",
    installApp: "Install app",
    updateReady: "Update ready",
    restartApp: "Restart",
    windowTooSmall: "Window is too small",
    openAudio: "Open audio",
    audioFileUpload: "Audio file upload",
    dropAudio: "Drop an audio file here",
    dropToOpen: "Drop to open",
    privacyNote: "Your file stays private, local, and is not uploaded.",
    supportedFormats: "Supports common audio and video formats.",
    waveformPlayer: "Waveform player",
    noFileLoaded: "No file loaded",
    ready: "Ready",
    interactiveWaveform: "Interactive audio waveform",
    waveformSeekHint: "Click or drag the waveform to seek",
    playbackPosition: "Playback position",
    play: "Play",
    pause: "Pause",
    nextSound: "Next section",
    timedJumpControls: "Timed jump controls",
    jumpBackward: "Jump backward",
    jumpForward: "Jump forward",
    jumpAmount: "Jump amount",
    back: "Back",
    forward: "Forward",
    volume: "Volume",
    speed: "Speed",
    processingAudio: "Processing audio",
    preparingWaveform: "Preparing waveform...",
    readingAudio: "Reading audio...",
    readingFile: "Reading file...",
    readingFileProgress: "Reading file... {percent}%",
    decodingAudio: "Decoding audio...",
    extractingAudio: "Extracting audio from video...",
    buildingWaveform: "Building waveform...",
    findingSilence: "Finding long silence gaps...",
    chooseAudioFile: "Choose an audio or video file.",
    unsupportedFile: "This file type is not supported. Choose a common audio or video file.",
    unsupportedCodec: "This file is recognized, but your browser cannot decode its codec. Try MP3, WAV, M4A/AAC, or WebM/Opus.",
    decodeError: "This file could not be decoded by the browser. Try a common audio or video format.",
    silenceStatus: "{count} long silence gap{plural} detected",
  },
  es: {
    language: "Idioma",
    settings: "Ajustes",
    closeSettings: "Cerrar ajustes",
    closeLicenses: "Cerrar licencias",
    displaySettings: "Pantalla",
    theme: "Tema",
    themeAuto: "Automático",
    themeDark: "Oscuro",
    themeLight: "Claro",
    detectionSettings: "Detección de silencio",
    silenceThreshold: "Umbral de silencio",
    minSilenceLength: "Silencio mínimo",
    minAudibleLength: "Audio mínimo",
    keyboardShortcuts: "Atajos de teclado",
    keySpace: "Espacio",
    keyEscape: "Esc",
    shortcutPlayPause: "Reproducir o pausar",
    shortcutJumpBack: "Saltar atrás",
    shortcutJumpForward: "Saltar adelante",
    shortcutNextSection: "Siguiente sección",
    shortcutCloseSettings: "Cerrar ajustes",
    resetDefaults: "Restablecer valores",
    licenses: "Licencias",
    openSourceLicenses: "Licencias de código abierto",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Las fuentes Material Symbols son proporcionadas por Google y están bajo la licencia Apache, versión 2.0.",
    installApp: "Instalar app",
    updateReady: "Actualización lista",
    restartApp: "Reiniciar",
    windowTooSmall: "La ventana es demasiado pequeña",
    openAudio: "Abrir audio",
    audioFileUpload: "Subir archivo de audio",
    dropAudio: "Suelta un archivo de audio aquí",
    dropToOpen: "Suelta para abrir",
    privacyNote: "Tu archivo sigue siendo privado, local y no se sube.",
    supportedFormats: "Compatible con formatos comunes de audio y video.",
    waveformPlayer: "Reproductor de forma de onda",
    noFileLoaded: "No hay archivo cargado",
    ready: "Listo",
    interactiveWaveform: "Forma de onda interactiva",
    waveformSeekHint: "Haz clic o arrastra la forma de onda para buscar",
    playbackPosition: "Posición de reproducción",
    play: "Reproducir",
    pause: "Pausar",
    nextSound: "Siguiente sección",
    timedJumpControls: "Controles de salto por tiempo",
    jumpBackward: "Saltar atrás",
    jumpForward: "Saltar adelante",
    jumpAmount: "Duración del salto",
    back: "Atrás",
    forward: "Adelante",
    volume: "Volumen",
    speed: "Velocidad",
    processingAudio: "Procesando audio",
    preparingWaveform: "Preparando forma de onda...",
    readingAudio: "Leyendo audio...",
    readingFile: "Leyendo archivo...",
    readingFileProgress: "Leyendo archivo... {percent}%",
    decodingAudio: "Decodificando audio...",
    extractingAudio: "Extrayendo audio del video...",
    buildingWaveform: "Creando forma de onda...",
    findingSilence: "Buscando pausas largas...",
    chooseAudioFile: "Elige un archivo de audio o video.",
    unsupportedFile: "Este tipo de archivo no es compatible. Elige un archivo común de audio o video.",
    unsupportedCodec: "El archivo se reconoce, pero el navegador no puede decodificar su códec. Prueba MP3, WAV, M4A/AAC o WebM/Opus.",
    decodeError: "El navegador no pudo decodificar este archivo. Prueba un formato común de audio o video.",
    silenceStatus: "Pausas largas detectadas: {count}",
  },
  fr: {
    language: "Langue",
    settings: "Réglages",
    closeSettings: "Fermer les réglages",
    closeLicenses: "Fermer les licences",
    displaySettings: "Affichage",
    theme: "Thème",
    themeAuto: "Auto",
    themeDark: "Sombre",
    themeLight: "Clair",
    detectionSettings: "Détection du silence",
    silenceThreshold: "Seuil de silence",
    minSilenceLength: "Silence minimum",
    minAudibleLength: "Audio minimum",
    keyboardShortcuts: "Raccourcis clavier",
    keySpace: "Espace",
    keyEscape: "Échap",
    shortcutPlayPause: "Lire ou mettre en pause",
    shortcutJumpBack: "Reculer",
    shortcutJumpForward: "Avancer",
    shortcutNextSection: "Section suivante",
    shortcutCloseSettings: "Fermer les réglages",
    resetDefaults: "Réinitialiser",
    licenses: "Licences",
    openSourceLicenses: "Licences open source",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Les polices Material Symbols sont fournies par Google et sous licence Apache, version 2.0.",
    installApp: "Installer l'app",
    updateReady: "Mise à jour prête",
    restartApp: "Redémarrer",
    windowTooSmall: "La fenêtre est trop petite",
    openAudio: "Ouvrir un audio",
    audioFileUpload: "Importer un fichier audio",
    dropAudio: "Déposez un fichier audio ici",
    dropToOpen: "Déposez pour ouvrir",
    privacyNote: "Votre fichier reste privé, local et n’est pas envoyé.",
    supportedFormats: "Prend en charge les formats audio et vidéo courants.",
    waveformPlayer: "Lecteur de forme d’onde",
    noFileLoaded: "Aucun fichier chargé",
    ready: "Prêt",
    interactiveWaveform: "Forme d’onde audio interactive",
    waveformSeekHint: "Cliquez ou faites glisser la forme d’onde pour naviguer",
    playbackPosition: "Position de lecture",
    play: "Lire",
    pause: "Pause",
    nextSound: "Section suivante",
    timedJumpControls: "Commandes de saut temporel",
    jumpBackward: "Reculer",
    jumpForward: "Avancer",
    jumpAmount: "Durée du saut",
    back: "Retour",
    forward: "Avance",
    volume: "Volume",
    speed: "Vitesse",
    processingAudio: "Traitement de l’audio",
    preparingWaveform: "Préparation de la forme d’onde...",
    readingAudio: "Lecture de l’audio...",
    readingFile: "Lecture du fichier...",
    readingFileProgress: "Lecture du fichier... {percent}%",
    decodingAudio: "Décodage de l’audio...",
    extractingAudio: "Extraction de l’audio de la vidéo...",
    buildingWaveform: "Création de la forme d’onde...",
    findingSilence: "Recherche des longues pauses...",
    chooseAudioFile: "Choisissez un fichier audio ou vidéo.",
    unsupportedFile: "Ce type de fichier n’est pas pris en charge. Choisissez un fichier audio ou vidéo courant.",
    unsupportedCodec: "Le fichier est reconnu, mais votre navigateur ne peut pas décoder son codec. Essayez MP3, WAV, M4A/AAC ou WebM/Opus.",
    decodeError: "Ce fichier n’a pas pu être décodé par le navigateur. Essayez un format audio ou vidéo courant.",
    silenceStatus: "Longues pauses détectées : {count}",
  },
  de: {
    language: "Sprache",
    settings: "Einstellungen",
    closeSettings: "Einstellungen schließen",
    closeLicenses: "Lizenzen schließen",
    displaySettings: "Anzeige",
    theme: "Design",
    themeAuto: "Automatisch",
    themeDark: "Dunkel",
    themeLight: "Hell",
    detectionSettings: "Stilleerkennung",
    silenceThreshold: "Stille-Schwelle",
    minSilenceLength: "Mindeststille",
    minAudibleLength: "Mindestaudio",
    keyboardShortcuts: "Tastenkürzel",
    keySpace: "Leertaste",
    keyEscape: "Esc",
    shortcutPlayPause: "Abspielen oder pausieren",
    shortcutJumpBack: "Zurückspringen",
    shortcutJumpForward: "Vorspringen",
    shortcutNextSection: "Nächster Abschnitt",
    shortcutCloseSettings: "Einstellungen schließen",
    resetDefaults: "Zurücksetzen",
    licenses: "Lizenzen",
    openSourceLicenses: "Open-Source-Lizenzen",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Material Symbols-Schriften werden von Google bereitgestellt und unter der Apache-Lizenz, Version 2.0, lizenziert.",
    installApp: "App installieren",
    updateReady: "Update bereit",
    restartApp: "Neu starten",
    windowTooSmall: "Fenster ist zu klein",
    openAudio: "Audio öffnen",
    audioFileUpload: "Audiodatei hochladen",
    dropAudio: "Audiodatei hier ablegen",
    dropToOpen: "Zum Öffnen ablegen",
    privacyNote: "Deine Datei bleibt privat, lokal und wird nicht hochgeladen.",
    supportedFormats: "Unterstützt gängige Audio- und Videoformate.",
    waveformPlayer: "Wellenform-Player",
    noFileLoaded: "Keine Datei geladen",
    ready: "Bereit",
    interactiveWaveform: "Interaktive Audio-Wellenform",
    waveformSeekHint: "Klicke oder ziehe die Wellenform zum Springen",
    playbackPosition: "Wiedergabeposition",
    play: "Abspielen",
    pause: "Pause",
    nextSound: "Nächster Abschnitt",
    timedJumpControls: "Zeit-Sprungsteuerung",
    jumpBackward: "Zurückspringen",
    jumpForward: "Vorspringen",
    jumpAmount: "Sprungweite",
    back: "Zurück",
    forward: "Vor",
    volume: "Lautstärke",
    speed: "Tempo",
    processingAudio: "Audio wird verarbeitet",
    preparingWaveform: "Wellenform wird vorbereitet...",
    readingAudio: "Audio wird gelesen...",
    readingFile: "Datei wird gelesen...",
    readingFileProgress: "Datei wird gelesen... {percent}%",
    decodingAudio: "Audio wird decodiert...",
    extractingAudio: "Audio wird aus dem Video extrahiert...",
    buildingWaveform: "Wellenform wird erstellt...",
    findingSilence: "Lange Stillepausen werden gesucht...",
    chooseAudioFile: "Wähle eine Audio- oder Videodatei.",
    unsupportedFile: "Dieser Dateityp wird nicht unterstützt. Wähle eine gängige Audio- oder Videodatei.",
    unsupportedCodec: "Die Datei wird erkannt, aber dein Browser kann ihren Codec nicht decodieren. Versuche MP3, WAV, M4A/AAC oder WebM/Opus.",
    decodeError: "Diese Datei konnte vom Browser nicht decodiert werden. Versuche ein gängiges Audio- oder Videoformat.",
    silenceStatus: "Lange Stillepausen erkannt: {count}",
  },
  "pt-BR": {
    language: "Idioma",
    settings: "Configurações",
    closeSettings: "Fechar configurações",
    closeLicenses: "Fechar licenças",
    displaySettings: "Exibição",
    theme: "Tema",
    themeAuto: "Auto",
    themeDark: "Escuro",
    themeLight: "Claro",
    detectionSettings: "Detecção de silêncio",
    silenceThreshold: "Limiar de silêncio",
    minSilenceLength: "Silêncio mínimo",
    minAudibleLength: "Áudio mínimo",
    keyboardShortcuts: "Atalhos de teclado",
    keySpace: "Espaço",
    keyEscape: "Esc",
    shortcutPlayPause: "Reproduzir ou pausar",
    shortcutJumpBack: "Voltar",
    shortcutJumpForward: "Avançar",
    shortcutNextSection: "Próxima seção",
    shortcutCloseSettings: "Fechar configurações",
    resetDefaults: "Restaurar padrões",
    licenses: "Licenças",
    openSourceLicenses: "Licenças de código aberto",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "As fontes Material Symbols são fornecidas pelo Google e licenciadas sob a Licença Apache, versão 2.0.",
    installApp: "Instalar app",
    updateReady: "Atualização pronta",
    restartApp: "Reiniciar",
    windowTooSmall: "A janela é muito pequena",
    openAudio: "Abrir áudio",
    audioFileUpload: "Enviar arquivo de áudio",
    dropAudio: "Solte um arquivo de áudio aqui",
    dropToOpen: "Solte para abrir",
    privacyNote: "Seu arquivo continua privado, local e não é enviado.",
    supportedFormats: "Compatível com formatos comuns de áudio e vídeo.",
    waveformPlayer: "Player de forma de onda",
    noFileLoaded: "Nenhum arquivo carregado",
    ready: "Pronto",
    interactiveWaveform: "Forma de onda interativa",
    waveformSeekHint: "Clique ou arraste a forma de onda para buscar",
    playbackPosition: "Posição de reprodução",
    play: "Reproduzir",
    pause: "Pausar",
    nextSound: "Próxima seção",
    timedJumpControls: "Controles de salto por tempo",
    jumpBackward: "Voltar",
    jumpForward: "Avançar",
    jumpAmount: "Duração do salto",
    back: "Voltar",
    forward: "Avançar",
    volume: "Volume",
    speed: "Velocidade",
    processingAudio: "Processando áudio",
    preparingWaveform: "Preparando forma de onda...",
    readingAudio: "Lendo áudio...",
    readingFile: "Lendo arquivo...",
    readingFileProgress: "Lendo arquivo... {percent}%",
    decodingAudio: "Decodificando áudio...",
    extractingAudio: "Extraindo áudio do vídeo...",
    buildingWaveform: "Criando forma de onda...",
    findingSilence: "Buscando pausas longas...",
    chooseAudioFile: "Escolha um arquivo de áudio ou vídeo.",
    unsupportedFile: "Este tipo de arquivo não é compatível. Escolha um arquivo comum de áudio ou vídeo.",
    unsupportedCodec: "O arquivo é reconhecido, mas o navegador não consegue decodificar o codec. Tente MP3, WAV, M4A/AAC ou WebM/Opus.",
    decodeError: "Este arquivo não pôde ser decodificado pelo navegador. Tente um formato comum de áudio ou vídeo.",
    silenceStatus: "Pausas longas detectadas: {count}",
  },
  ru: {
    language: "Язык",
    settings: "Настройки",
    closeSettings: "Закрыть настройки",
    closeLicenses: "Закрыть лицензии",
    displaySettings: "Отображение",
    theme: "Тема",
    themeAuto: "Авто",
    themeDark: "Темная",
    themeLight: "Светлая",
    detectionSettings: "Определение тишины",
    silenceThreshold: "Порог тишины",
    minSilenceLength: "Минимальная тишина",
    minAudibleLength: "Минимальный звук",
    keyboardShortcuts: "Горячие клавиши",
    keySpace: "Пробел",
    keyEscape: "Esc",
    shortcutPlayPause: "Воспроизвести или пауза",
    shortcutJumpBack: "Назад",
    shortcutJumpForward: "Вперед",
    shortcutNextSection: "Следующий участок",
    shortcutCloseSettings: "Закрыть настройки",
    resetDefaults: "Сбросить настройки",
    licenses: "Лицензии",
    openSourceLicenses: "Лицензии открытого кода",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Шрифты Material Symbols предоставляются Google и лицензируются по лицензии Apache версии 2.0.",
    installApp: "Установить",
    updateReady: "Обновление готово",
    restartApp: "Перезапустить",
    windowTooSmall: "Окно слишком маленькое",
    openAudio: "Открыть аудио",
    audioFileUpload: "Загрузка аудиофайла",
    dropAudio: "Перетащите аудиофайл сюда",
    dropToOpen: "Перетащите, чтобы открыть",
    privacyNote: "Файл остается приватным, локальным и не загружается.",
    supportedFormats: "Поддерживаются распространенные форматы аудио и видео.",
    waveformPlayer: "Плеер формы волны",
    noFileLoaded: "Файл не загружен",
    ready: "Готово",
    interactiveWaveform: "Интерактивная звуковая волна",
    waveformSeekHint: "Нажмите или перетащите волну, чтобы перейти",
    playbackPosition: "Позиция воспроизведения",
    play: "Воспроизвести",
    pause: "Пауза",
    nextSound: "Следующий участок",
    timedJumpControls: "Переходы по времени",
    jumpBackward: "Назад",
    jumpForward: "Вперед",
    jumpAmount: "Шаг перехода",
    back: "Назад",
    forward: "Вперед",
    volume: "Громкость",
    speed: "Скорость",
    processingAudio: "Обработка аудио",
    preparingWaveform: "Подготовка формы волны...",
    readingAudio: "Чтение аудио...",
    readingFile: "Чтение файла...",
    readingFileProgress: "Чтение файла... {percent}%",
    decodingAudio: "Декодирование аудио...",
    extractingAudio: "Извлечение аудио из видео...",
    buildingWaveform: "Построение формы волны...",
    findingSilence: "Поиск длинных пауз...",
    chooseAudioFile: "Выберите аудио- или видеофайл.",
    unsupportedFile: "Этот тип файла не поддерживается. Выберите распространенный аудио- или видеофайл.",
    unsupportedCodec: "Файл распознан, но браузер не может декодировать его кодек. Попробуйте MP3, WAV, M4A/AAC или WebM/Opus.",
    decodeError: "Браузер не смог декодировать этот файл. Попробуйте распространенный формат аудио или видео.",
    silenceStatus: "Длинные паузы найдены: {count}",
  },
  hi: {
    language: "भाषा",
    settings: "सेटिंग्स",
    closeSettings: "सेटिंग्स बंद करें",
    closeLicenses: "लाइसेंस बंद करें",
    displaySettings: "डिस्प्ले",
    theme: "थीम",
    themeAuto: "ऑटो",
    themeDark: "डार्क",
    themeLight: "लाइट",
    detectionSettings: "साइलेंस डिटेक्शन",
    silenceThreshold: "साइलेंस थ्रेशहोल्ड",
    minSilenceLength: "न्यूनतम साइलेंस",
    minAudibleLength: "न्यूनतम ऑडियो",
    keyboardShortcuts: "कीबोर्ड शॉर्टकट",
    keySpace: "स्पेस",
    keyEscape: "Esc",
    shortcutPlayPause: "चलाएं या रोकें",
    shortcutJumpBack: "पीछे जाएं",
    shortcutJumpForward: "आगे जाएं",
    shortcutNextSection: "अगला सेक्शन",
    shortcutCloseSettings: "सेटिंग्स बंद करें",
    resetDefaults: "डिफ़ॉल्ट रीसेट करें",
    licenses: "लाइसेंस",
    openSourceLicenses: "ओपन सोर्स लाइसेंस",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Material Symbols फ़ॉन्ट Google द्वारा प्रदान किए जाते हैं और Apache License, Version 2.0 के तहत लाइसेंस प्राप्त हैं।",
    installApp: "ऐप इंस्टॉल करें",
    updateReady: "अपडेट तैयार है",
    restartApp: "रीस्टार्ट करें",
    windowTooSmall: "विंडो बहुत छोटी है",
    openAudio: "ऑडियो खोलें",
    audioFileUpload: "ऑडियो फ़ाइल अपलोड",
    dropAudio: "ऑडियो फ़ाइल यहां छोड़ें",
    dropToOpen: "खोलने के लिए छोड़ें",
    privacyNote: "आपकी फ़ाइल निजी और लोकल रहती है, अपलोड नहीं होती।",
    supportedFormats: "सामान्य ऑडियो और वीडियो फ़ॉर्मैट समर्थित हैं।",
    waveformPlayer: "वेवफ़ॉर्म प्लेयर",
    noFileLoaded: "कोई फ़ाइल लोड नहीं है",
    ready: "तैयार",
    interactiveWaveform: "इंटरैक्टिव ऑडियो वेवफ़ॉर्म",
    waveformSeekHint: "सीक करने के लिए वेवफ़ॉर्म पर क्लिक या ड्रैग करें",
    playbackPosition: "प्लेबैक स्थिति",
    play: "चलाएं",
    pause: "रोकें",
    nextSound: "अगला सेक्शन",
    timedJumpControls: "समय जंप कंट्रोल",
    jumpBackward: "पीछे जाएं",
    jumpForward: "आगे जाएं",
    jumpAmount: "जंप अवधि",
    back: "पीछे",
    forward: "आगे",
    volume: "वॉल्यूम",
    speed: "स्पीड",
    processingAudio: "ऑडियो प्रोसेस हो रहा है",
    preparingWaveform: "वेवफ़ॉर्म तैयार हो रहा है...",
    readingAudio: "ऑडियो पढ़ा जा रहा है...",
    readingFile: "फ़ाइल पढ़ी जा रही है...",
    readingFileProgress: "फ़ाइल पढ़ी जा रही है... {percent}%",
    decodingAudio: "ऑडियो डिकोड हो रहा है...",
    extractingAudio: "वीडियो से ऑडियो निकाला जा रहा है...",
    buildingWaveform: "वेवफ़ॉर्म बन रहा है...",
    findingSilence: "लंबे साइलेंस गैप ढूंढे जा रहे हैं...",
    chooseAudioFile: "ऑडियो या वीडियो फ़ाइल चुनें।",
    unsupportedFile: "यह फ़ाइल प्रकार समर्थित नहीं है। सामान्य ऑडियो या वीडियो फ़ाइल चुनें।",
    unsupportedCodec: "फ़ाइल पहचानी गई है, लेकिन ब्राउज़र इसका कोडेक डिकोड नहीं कर सकता। MP3, WAV, M4A/AAC या WebM/Opus आज़माएँ।",
    decodeError: "ब्राउज़र इस फ़ाइल को डिकोड नहीं कर सका। कोई सामान्य ऑडियो या वीडियो फ़ॉर्मैट आज़माएँ।",
    silenceStatus: "{count} लंबे साइलेंस गैप मिले",
  },
  ja: {
    language: "言語",
    settings: "設定",
    closeSettings: "設定を閉じる",
    closeLicenses: "ライセンスを閉じる",
    displaySettings: "表示",
    theme: "テーマ",
    themeAuto: "自動",
    themeDark: "ダーク",
    themeLight: "ライト",
    detectionSettings: "無音検出",
    silenceThreshold: "無音しきい値",
    minSilenceLength: "最短無音時間",
    minAudibleLength: "最短有音時間",
    keyboardShortcuts: "キーボードショートカット",
    keySpace: "スペース",
    keyEscape: "Esc",
    shortcutPlayPause: "再生または一時停止",
    shortcutJumpBack: "戻る",
    shortcutJumpForward: "進む",
    shortcutNextSection: "次の区間",
    shortcutCloseSettings: "設定を閉じる",
    resetDefaults: "初期値に戻す",
    licenses: "ライセンス",
    openSourceLicenses: "オープンソースライセンス",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Material Symbols フォントは Google により提供され、Apache License, Version 2.0 のもとでライセンスされています。",
    installApp: "アプリをインストール",
    updateReady: "更新の準備ができました",
    restartApp: "再起動",
    windowTooSmall: "ウィンドウが小さすぎます",
    openAudio: "音声を開く",
    audioFileUpload: "音声ファイルをアップロード",
    dropAudio: "ここに音声ファイルをドロップ",
    dropToOpen: "ドロップして開く",
    privacyNote: "ファイルはローカルでのみ処理され、アップロードされません。",
    supportedFormats: "一般的な音声・動画形式に対応しています。",
    waveformPlayer: "波形プレーヤー",
    noFileLoaded: "ファイルが読み込まれていません",
    ready: "準備完了",
    interactiveWaveform: "操作できる音声波形",
    waveformSeekHint: "波形をクリックまたはドラッグして移動",
    playbackPosition: "再生位置",
    play: "再生",
    pause: "一時停止",
    nextSound: "次の区間",
    timedJumpControls: "時間ジャンプ操作",
    jumpBackward: "戻る",
    jumpForward: "進む",
    jumpAmount: "ジャンプ量",
    back: "戻る",
    forward: "進む",
    volume: "音量",
    speed: "速度",
    processingAudio: "音声を処理中",
    preparingWaveform: "波形を準備中...",
    readingAudio: "音声を読み込み中...",
    readingFile: "ファイルを読み込み中...",
    readingFileProgress: "ファイルを読み込み中... {percent}%",
    decodingAudio: "音声をデコード中...",
    extractingAudio: "動画から音声を抽出中...",
    buildingWaveform: "波形を作成中...",
    findingSilence: "長い無音区間を検出中...",
    chooseAudioFile: "音声または動画ファイルを選択してください。",
    unsupportedFile: "このファイル形式には対応していません。一般的な音声または動画ファイルを選択してください。",
    unsupportedCodec: "ファイルは認識されましたが、ブラウザがそのコーデックをデコードできません。MP3、WAV、M4A/AAC、WebM/Opus を試してください。",
    decodeError: "このファイルはブラウザでデコードできませんでした。一般的な音声または動画形式を試してください。",
    silenceStatus: "長い無音区間を{count}件検出しました",
  },
  ko: {
    language: "언어",
    settings: "설정",
    closeSettings: "설정 닫기",
    closeLicenses: "라이선스 닫기",
    displaySettings: "화면",
    theme: "테마",
    themeAuto: "자동",
    themeDark: "어둡게",
    themeLight: "밝게",
    detectionSettings: "무음 감지",
    silenceThreshold: "무음 임계값",
    minSilenceLength: "최소 무음 길이",
    minAudibleLength: "최소 오디오 길이",
    keyboardShortcuts: "키보드 단축키",
    keySpace: "스페이스",
    keyEscape: "Esc",
    shortcutPlayPause: "재생 또는 일시정지",
    shortcutJumpBack: "뒤로 이동",
    shortcutJumpForward: "앞으로 이동",
    shortcutNextSection: "다음 구간",
    shortcutCloseSettings: "설정 닫기",
    resetDefaults: "기본값 재설정",
    licenses: "라이선스",
    openSourceLicenses: "오픈소스 라이선스",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Material Symbols 글꼴은 Google에서 제공하며 Apache License, Version 2.0에 따라 라이선스됩니다.",
    installApp: "앱 설치",
    updateReady: "업데이트 준비됨",
    restartApp: "다시 시작",
    windowTooSmall: "창이 너무 작습니다",
    openAudio: "오디오 열기",
    audioFileUpload: "오디오 파일 업로드",
    dropAudio: "여기에 오디오 파일을 놓으세요",
    dropToOpen: "놓아서 열기",
    privacyNote: "파일은 로컬에서만 처리되며 업로드되지 않습니다.",
    supportedFormats: "일반적인 오디오 및 비디오 형식을 지원합니다.",
    waveformPlayer: "파형 플레이어",
    noFileLoaded: "불러온 파일 없음",
    ready: "준비됨",
    interactiveWaveform: "대화형 오디오 파형",
    waveformSeekHint: "파형을 클릭하거나 드래그해서 이동",
    playbackPosition: "재생 위치",
    play: "재생",
    pause: "일시정지",
    nextSound: "다음 구간",
    timedJumpControls: "시간 이동 컨트롤",
    jumpBackward: "뒤로 이동",
    jumpForward: "앞으로 이동",
    jumpAmount: "이동 시간",
    back: "뒤로",
    forward: "앞으로",
    volume: "볼륨",
    speed: "속도",
    processingAudio: "오디오 처리 중",
    preparingWaveform: "파형 준비 중...",
    readingAudio: "오디오 읽는 중...",
    readingFile: "파일 읽는 중...",
    readingFileProgress: "파일 읽는 중... {percent}%",
    decodingAudio: "오디오 디코딩 중...",
    extractingAudio: "비디오에서 오디오 추출 중...",
    buildingWaveform: "파형 만드는 중...",
    findingSilence: "긴 무음 구간 찾는 중...",
    chooseAudioFile: "오디오 또는 비디오 파일을 선택하세요.",
    unsupportedFile: "이 파일 형식은 지원되지 않습니다. 일반적인 오디오 또는 비디오 파일을 선택하세요.",
    unsupportedCodec: "파일은 인식되었지만 브라우저가 해당 코덱을 디코딩할 수 없습니다. MP3, WAV, M4A/AAC 또는 WebM/Opus를 사용해 보세요.",
    decodeError: "브라우저에서 이 파일을 디코딩할 수 없습니다. 일반적인 오디오 또는 비디오 형식을 사용해 보세요.",
    silenceStatus: "긴 무음 구간 {count}개를 찾았습니다",
  },
  "zh-CN": {
    language: "语言",
    settings: "设置",
    closeSettings: "关闭设置",
    closeLicenses: "关闭许可证",
    displaySettings: "显示",
    theme: "主题",
    themeAuto: "自动",
    themeDark: "深色",
    themeLight: "浅色",
    detectionSettings: "静音检测",
    silenceThreshold: "静音阈值",
    minSilenceLength: "最短静音时长",
    minAudibleLength: "最短有声时长",
    keyboardShortcuts: "键盘快捷键",
    keySpace: "空格",
    keyEscape: "Esc",
    shortcutPlayPause: "播放或暂停",
    shortcutJumpBack: "向后跳转",
    shortcutJumpForward: "向前跳转",
    shortcutNextSection: "下一段",
    shortcutCloseSettings: "关闭设置",
    resetDefaults: "恢复默认",
    licenses: "许可证",
    openSourceLicenses: "开源许可证",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Material Symbols 字体由 Google 提供，并根据 Apache License, Version 2.0 授权。",
    installApp: "安装应用",
    updateReady: "更新已就绪",
    restartApp: "重启",
    windowTooSmall: "窗口太小",
    openAudio: "打开音频",
    audioFileUpload: "上传音频文件",
    dropAudio: "将音频文件拖到这里",
    dropToOpen: "拖放以打开",
    privacyNote: "你的文件只在本地处理，不会上传。",
    supportedFormats: "支持常见音频和视频格式。",
    waveformPlayer: "波形播放器",
    noFileLoaded: "未加载文件",
    ready: "准备就绪",
    interactiveWaveform: "可交互音频波形",
    waveformSeekHint: "点击或拖动波形以跳转",
    playbackPosition: "播放位置",
    play: "播放",
    pause: "暂停",
    nextSound: "下一段",
    timedJumpControls: "定时跳转控件",
    jumpBackward: "向后跳转",
    jumpForward: "向前跳转",
    jumpAmount: "跳转时长",
    back: "后退",
    forward: "前进",
    volume: "音量",
    speed: "速度",
    processingAudio: "正在处理音频",
    preparingWaveform: "正在准备波形...",
    readingAudio: "正在读取音频...",
    readingFile: "正在读取文件...",
    readingFileProgress: "正在读取文件... {percent}%",
    decodingAudio: "正在解码音频...",
    extractingAudio: "正在从视频中提取音频...",
    buildingWaveform: "正在生成波形...",
    findingSilence: "正在查找较长静音段...",
    chooseAudioFile: "请选择音频或视频文件。",
    unsupportedFile: "不支持此文件类型。请选择常见的音频或视频文件。",
    unsupportedCodec: "文件已识别，但浏览器无法解码其编解码器。请尝试 MP3、WAV、M4A/AAC 或 WebM/Opus。",
    decodeError: "浏览器无法解码此文件。请尝试常见的音频或视频格式。",
    silenceStatus: "检测到 {count} 个较长静音段",
  },
  "zh-TW": {
    language: "語言",
    settings: "設定",
    closeSettings: "關閉設定",
    closeLicenses: "關閉授權條款",
    displaySettings: "顯示",
    theme: "主題",
    themeAuto: "自動",
    themeDark: "深色",
    themeLight: "淺色",
    detectionSettings: "靜音偵測",
    silenceThreshold: "靜音閾值",
    minSilenceLength: "最短靜音長度",
    minAudibleLength: "最短有聲長度",
    keyboardShortcuts: "鍵盤快捷鍵",
    keySpace: "空白鍵",
    keyEscape: "Esc",
    shortcutPlayPause: "播放或暫停",
    shortcutJumpBack: "向後跳轉",
    shortcutJumpForward: "向前跳轉",
    shortcutNextSection: "下一段",
    shortcutCloseSettings: "關閉設定",
    resetDefaults: "恢復預設",
    licenses: "授權條款",
    openSourceLicenses: "開源授權條款",
    materialSymbolsLicense: "Material Symbols",
    materialSymbolsLicenseSummary: "Material Symbols 字型由 Google 提供，並依 Apache License, Version 2.0 授權。",
    installApp: "安裝 App",
    updateReady: "更新已就緒",
    restartApp: "重新啟動",
    windowTooSmall: "視窗太小",
    openAudio: "開啟音訊",
    audioFileUpload: "上傳音訊檔",
    dropAudio: "將音訊檔拖放到這裡",
    dropToOpen: "拖放以開啟",
    privacyNote: "你的檔案只會在本機處理，不會上傳。",
    supportedFormats: "支援常見音訊和影片格式。",
    waveformPlayer: "波形播放器",
    noFileLoaded: "尚未載入檔案",
    ready: "準備就緒",
    interactiveWaveform: "可互動音訊波形",
    waveformSeekHint: "點擊或拖曳波形以跳轉",
    playbackPosition: "播放位置",
    play: "播放",
    pause: "暫停",
    nextSound: "下一段",
    timedJumpControls: "定時跳轉控制",
    jumpBackward: "向後跳轉",
    jumpForward: "向前跳轉",
    jumpAmount: "跳轉長度",
    back: "返回",
    forward: "前進",
    volume: "音量",
    speed: "速度",
    processingAudio: "正在處理音訊",
    preparingWaveform: "正在準備波形...",
    readingAudio: "正在讀取音訊...",
    readingFile: "正在讀取檔案...",
    readingFileProgress: "正在讀取檔案... {percent}%",
    decodingAudio: "正在解碼音訊...",
    extractingAudio: "正在從影片中擷取音訊...",
    buildingWaveform: "正在產生波形...",
    findingSilence: "正在尋找較長靜音段...",
    chooseAudioFile: "請選擇音訊或影片檔。",
    unsupportedFile: "不支援此檔案類型。請選擇常見的音訊或影片檔。",
    unsupportedCodec: "檔案已識別，但瀏覽器無法解碼其編解碼器。請嘗試 MP3、WAV、M4A/AAC 或 WebM/Opus。",
    decodeError: "瀏覽器無法解碼此檔案。請嘗試常見的音訊或影片格式。",
    silenceStatus: "偵測到 {count} 個較長靜音段",
  },
};

const STORAGE_KEY = "audioNavigatorSettings";
const WAVEFORM_HINT_STORAGE_KEY = `audioNavigatorWaveformHint:${APP_VERSION}`;
const DEFAULT_SETTINGS = {
  theme: "auto",
  silenceThreshold: 0.01,
  minSilenceSeconds: 12,
  minAudibleSeconds: 0.2,
};
function clampNumber(value, min, max) {
  if (!Number.isFinite(value)) {
    return min;
  }
  return Math.min(max, Math.max(min, value));
}

function getLanguagePreference() {
  const supportedLanguages = Object.keys(translations);
  const preferredLanguages = navigator.languages?.length ? navigator.languages : [navigator.language];

  for (const language of preferredLanguages) {
    const match = getSupportedLanguage(language, supportedLanguages);
    if (match) {
      return {
        language: match,
        isSupported: true,
      };
    }
  }

  return {
    language: "en",
    isSupported: false,
  };
}

function getSupportedLanguage(language, supportedLanguages) {
  if (!language) {
    return "";
  }

  const normalizedLanguage = language.trim();
  if (supportedLanguages.includes(normalizedLanguage)) {
    return normalizedLanguage;
  }

  const baseLanguage = normalizedLanguage.split("-")[0];
  return supportedLanguages.find((item) => item === baseLanguage || item.startsWith(`${baseLanguage}-`)) || "";
}

function normalizeStoredSettings(storedSettings, defaultLanguage) {
  const stored = parseStoredSettings(storedSettings);
  const fallback = {
    ...DEFAULT_SETTINGS,
    language: defaultLanguage,
  };

  const language = translations[stored.language] ? stored.language : fallback.language;
  const theme = ["auto", "dark", "light"].includes(stored.theme) ? stored.theme : fallback.theme;
  return {
    language,
    theme,
    silenceThreshold: clampNumber(Number(stored.silenceThreshold ?? fallback.silenceThreshold), 0.005, 0.08),
    minSilenceSeconds: clampNumber(Number(stored.minSilenceSeconds ?? fallback.minSilenceSeconds), 1, 30),
    minAudibleSeconds: clampNumber(Number(stored.minAudibleSeconds ?? fallback.minAudibleSeconds), 0.1, 3),
  };
}

function parseStoredSettings(storedSettings) {
  if (!storedSettings) {
    return {};
  }

  if (typeof storedSettings === "string") {
    try {
      return JSON.parse(storedSettings) || {};
    } catch (error) {
      return {};
    }
  }

  return typeof storedSettings === "object" ? storedSettings : {};
}

function getSavedSettings(defaultLanguage) {
  try {
    return normalizeStoredSettings(localStorage.getItem(STORAGE_KEY), defaultLanguage);
  } catch (error) {
    return normalizeStoredSettings({}, defaultLanguage);
  }
}

const languagePreference = getLanguagePreference();
const savedSettings = getSavedSettings(languagePreference.language);

const state = {
  language: savedSettings.language,
  hasSupportedBrowserLanguage: languagePreference.isSupported,
  settings: {
    theme: savedSettings.theme,
    silenceThreshold: savedSettings.silenceThreshold,
    minSilenceSeconds: savedSettings.minSilenceSeconds,
    minAudibleSeconds: savedSettings.minAudibleSeconds,
  },
  settingsStorageHydrated: false,
  settingsChangedBeforeHydration: false,
  audioBuffer: null,
  analysisDuration: 0,
  mediaDuration: 0,
  playbackBackend: "buffer",
  mediaElement: null,
  mediaElementSource: null,
  mediaObjectUrl: "",
  monoSamples: null,
  peaks: [],
  rmsFrames: [],
  regions: [],
  silentRegions: [],
  threshold: 0,
  audioContext: null,
  audioSource: null,
  gainNode: null,
  boostShaperNode: null,
  limiterNode: null,
  playbackOffset: 0,
  playbackStartedAt: 0,
  playbackRate: 1,
  isPlaying: false,
  jumpAmount: 10,
  statusKey: "ready",
  statusParams: {},
  errorKey: "",
  busyTitleKey: "processingAudio",
  busyDetailKey: "preparingWaveform",
  busyDetailParams: {},
  isPointerSeeking: false,
  isWaveformHovering: false,
  waveformHoverTime: 0,
  waveformHintTimer: 0,
  animationFrame: 0,
  resizeFrame: 0,
  viewportWarningFrame: 0,
  deferredInstallPrompt: null,
  pwaWaitingWorker: null,
  pwaReloadingForUpdate: false,
  globalDragDepth: 0,
  globalDragResetTimer: 0,
  boostCurveKey: "",
  staticWaveformCanvas: null,
  staticWaveformContext: null,
  canvasPixelWidth: 0,
  canvasPixelHeight: 0,
  lastCurrentTimeText: "",
  lastDurationText: "",
  lastTimelineValue: "",
};

const RMS_WINDOW_SECONDS = 0.05;
const SEEK_EPSILON = 0.08;
const ANALYSIS_CHUNK_DURATION_MS = 16;
const LONG_FILE_MEMORY_SAVE_SECONDS = 30 * 60;
const DESKTOP_MIN_INTERACTIVE_WIDTH = 760;
const SUPPORTED_AUDIO_EXTENSIONS = new Set(["aac", "flac", "m4a", "mp3", "oga", "ogg", "opus", "wav", "weba"]);
const SUPPORTED_VIDEO_EXTENSIONS = new Set(["avi", "m4v", "mkv", "mov", "mp4", "webm"]);
const RECORDED_AUDIO_MIME_TYPES = [
  "audio/webm;codecs=opus",
  "audio/webm",
  "audio/ogg;codecs=opus",
  "audio/ogg",
  "audio/mp4",
];
const PWA_THEME_COLORS = {
  light: "#3D59F5",
  dark: "#242833",
};

class UnsupportedMediaError extends Error {
  constructor(message = "Unsupported media file.") {
    super(message);
    this.name = "UnsupportedMediaError";
  }
}
